server:
  port: 8088

springfox:
  documentation:
    enabled: true

spring:
  datasource: #数据库相关
    url: jdbc:mysql://localhost:3306/order?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
